"""initial migration

Revision ID: 6c9839be2ce3
Revises: 
Create Date: 2017-02-10 16:04:02.641000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c9839be2ce3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PasteFile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=5000), nullable=False),
    sa.Column('filehash', sa.String(length=128), nullable=False),
    sa.Column('filemd5', sa.String(length=128), nullable=False),
    sa.Column('uploadtime', sa.DateTime(), nullable=False),
    sa.Column('mimetype', sa.String(length=256), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filehash'),
    sa.UniqueConstraint('filemd5')
    )
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('pastefile')
    op.drop_table('articles')
    op.drop_table('about')
    op.drop_table('user')
    op.drop_table('test')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('body', mysql.TEXT(), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('test',
    sa.Column('name', mysql.CHAR(length=1), nullable=False),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('about',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('auth', mysql.TEXT(), nullable=True),
    sa.Column('website', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('articles',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('content', mysql.VARCHAR(length=5000), nullable=True),
    sa.Column('pub_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('pastefile',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('filehash', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('flename', mysql.VARCHAR(length=5000), nullable=False),
    sa.Column('filemd5', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('uploadtime', mysql.DATETIME(), nullable=False),
    sa.Column('mimetype', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('size', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('roles',
    sa.Column('id', mysql.TINYINT(display_width=3, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('_default', mysql.CHAR(length=64), nullable=True),
    sa.Column('permissions', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.CHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('role_id', mysql.TINYINT(display_width=3, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('confirmed', mysql.TINYINT(display_width=1), server_default=sa.text(u"'0'"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], [u'roles.id'], name=u'em_fk_dep'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('PasteFile')
    # ### end Alembic commands ###
