"""initial migration

Revision ID: 6c9839be2ce3
Revises: 
Create Date: 2017-02-10 16:04:02.641000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c9839be2ce3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PasteFile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=5000), nullable=False),
    sa.Column('filehash', sa.String(length=128), nullable=False),
    sa.Column('filemd5', sa.String(length=128), nullable=False),
    sa.Column('uploadtime', sa.DateTime(), nullable=False),
    sa.Column('mimetype', sa.String(length=256), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filehash'),
    sa.UniqueConstraint('filemd5')
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('pastefile',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('filehash', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('flename', mysql.VARCHAR(length=5000), nullable=False),
    sa.Column('filemd5', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('uploadtime', mysql.DATETIME(), nullable=False),
    sa.Column('mimetype', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('size', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    
    op.drop_table('PasteFile')
    # ### end Alembic commands ###
